### ISSUE TITLE
"100 eur in usd" currency conversion throws

### ISSUE THREAD

**Issue by adalon** [KirillOsenkov/QuickInfo#36]
System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).) ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.<GetStringAsyncCore>d__27.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at QuickInfo.Currency.GetRate(String from, String to) in C:\QuickInfo\src\QuickInfo\Processors\Converters\Currency.cs:line 35
   at QuickInfo.Currency.<>c__DisplayClass4_0.<Convert>b__0(ICacheEntry e) in C:\QuickInfo\src\QuickInfo\Processors\Converters\Currency.cs:line 25
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at QuickInfo.Currency.Convert(String from, String to, Double value) in C:\QuickInfo\src\QuickInfo\Processors\Converters\Currency.cs:line 21
   at QuickInfo.Units.<>c.<.cctor>b__64_90(Double p) in C:\QuickInfo\src\QuickInfo\Processors\Converters\Units\Units.cs:line 175
   at QuickInfo.UnitConverter.GetResult(Double value, Conversion conversion) in C:\QuickInfo\src\QuickInfo\Processors\Converters\Units\UnitConverter.cs:line 251
   at QuickInfo.UnitConverter.GetResult(Double value, Unit unit, Unit toUnit) in C:\QuickInfo\src\QuickInfo\Processors\Converters\Units\UnitConverter.cs:line 179
   at QuickInfo.UnitConverter.GetResult(Query query) in C:\QuickInfo\src\QuickInfo\Processors\Converters\Units\UnitConverter.cs:line 106
   at QuickInfo.Engine.GetResults(Query query) in C:\QuickInfo\src\QuickInfo\Engine.cs:line 55
   at QuickInfo.Controllers.AnswersController.GetSingleResponseWorker(Engine engine, String input, HttpRequest request) in C:\QuickInfo\src\QuickInfoWeb\Controllers\AnswersController.cs:line 101
   at QuickInfo.Controllers.AnswersController.GetResponse(Engine engine, String input, HttpRequest request) in C:\QuickInfo\src\QuickInfoWeb\Controllers\AnswersController.cs:line 84
   at QuickInfo.Controllers.AnswersController.Get(String query) in C:\QuickInfo\src\QuickInfoWeb\Controllers\AnswersController.cs:line 16
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.<GetStringAsyncCore>d__27.MoveNext()<---

**Comment by KirillOsenkov** [comment]
Ah, they have changed their API:
https://api.fixer.io/latest

I will update.

**Comment by KirillOsenkov** [comment]
Should be fixed.
