### ISSUE TITLE
tes

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/QuickInfo#66]
Searching for `tes` results in:

```
System.ArgumentOutOfRangeException: A valid UTF32 value is between 0x000000 and 0x10ffff, inclusive, and should not include surrogate codepoint values (0x00d800 ~ 0x00dfff). (Parameter 'utf32')
   at System.Char.ConvertFromUtf32(Int32 utf32)
   at QuickInfo.Unicode.GetEscapeString(Int32 value) in D:\a\1\s\src\QuickInfo\Processors\Unicode.cs:line 304
   at QuickInfo.Unicode.GetResult(Int32 value, Boolean useCard) in D:\a\1\s\src\QuickInfo\Processors\Unicode.cs:line 288
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at QuickInfo.Unicode.ListBlock(UnicodeBlock block) in D:\a\1\s\src\QuickInfo\Processors\Unicode.cs:line 139
   at QuickInfo.Unicode.GetResult(Query query) in D:\a\1\s\src\QuickInfo\Processors\Unicode.cs:line 121
   at QuickInfo.Engine.GetResults(Query query) in D:\a\1\s\src\QuickInfo\Engine.cs:line 55
   at QuickInfo.Controllers.AnswersController.GetSingleResponseWorker(Engine engine, String input, HttpRequest request) in D:\a\1\s\src\QuickInfoWeb\Controllers\AnswersController.cs:line 102
   at QuickInfo.Controllers.AnswersController.GetResponse(Engine engine, String input, HttpRequest request) in D:\a\1\s\src\QuickInfoWeb\Controllers\AnswersController.cs:line 85
   at QuickInfo.Controllers.AnswersController.Get(String query) in D:\a\1\s\src\QuickInfoWeb\Controllers\AnswersController.cs:line 35
```

**Comment by KirillOsenkov** [comment]
Thanks to @paulomorgado
