### ISSUE TITLE
there is an exception after in "color" in search box

### ISSUE THREAD

**Issue by demiwang2020** [KirillOsenkov/QuickInfo#80]
System.TypeInitializationException: The type initializer for 'QuickInfo.Controllers.AnswersController' threw an exception.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'System.Unicode.UnicodeInfo' threw an exception.
 ---> System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at System.Unicode.UnicodeData.ReadUnicodeCharacterDataEntry(BinaryReader reader, Byte[] nameBuffer, UnicodeCharacterData& value)
   at System.Unicode.UnicodeData.ReadFromStream(Stream stream)
   at System.Unicode.UnicodeData.ReadFromResources()
   at System.Unicode.UnicodeInfo..cctor()
   --- End of inner exception stack trace ---
   at System.Unicode.UnicodeInfo.GetBlocks()
   at QuickInfo.Unicode.BuildUnicodeList() in D:\QuickInfo\src\QuickInfo\Processors\Unicode.cs:line 194
   at QuickInfo.Unicode..ctor() in D:\QuickInfo\src\QuickInfo\Processors\Unicode.cs:line 22
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at QuickInfo.Engine.<>c.<.ctor>b__2_1(Type t) in D:\QuickInfo\src\QuickInfo\Engine.cs:line 28
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at QuickInfo.Engine..ctor(Assembly[] assemblies) in D:\QuickInfo\src\QuickInfo\Engine.cs:line 28
   at QuickInfo.Controllers.AnswersController..cctor() in D:\QuickInfo\src\QuickInfoWeb\Controllers\AnswersController.cs:line 40
   --- End of inner exception stack trace ---
   at QuickInfo.Controllers.AnswersController.get_Instance() in D:\QuickInfo\src\QuickInfoWeb\Controllers\AnswersController.cs:line 40
   at QuickInfo.Controllers.AnswersController.Get(String query) in D:\QuickInfo\src\QuickInfoWeb\Controllers\AnswersController.cs:line 20

**Comment by KirillOsenkov** [comment]
Do you have a screenshot? Or a hyperlink to what you've typed? Are you trying to run it locally?

**Comment by KirillOsenkov** [comment]
I tried and it works fine on my machine. Just `cd src\QuickInfoWeb` and type `dotnet run`.
